
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LicRegVCRDetailsSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LicRegVCRDetailsSoap {


    /**
     * 
     * @param licenseNo
     * @param regnNo
     * @param documentType
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetLicRegVCRDetails", action = "http://tempuri.org/GetLicRegVCRDetails")
    @WebResult(name = "GetLicRegVCRDetailsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetLicRegVCRDetails", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetLicRegVCRDetails")
    @ResponseWrapper(localName = "GetLicRegVCRDetailsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetLicRegVCRDetailsResponse")
    public String getLicRegVCRDetails(
        @WebParam(name = "document_type", targetNamespace = "http://tempuri.org/")
        String documentType,
        @WebParam(name = "LicenseNo", targetNamespace = "http://tempuri.org/")
        String licenseNo,
        @WebParam(name = "RegnNo", targetNamespace = "http://tempuri.org/")
        String regnNo);

    /**
     * 
     * @param paymentDt
     * @param challanNo
     * @param regnNo
     * @param transactionAmount
     * @param transactionNo
     * @param transactionDt
     * @param vcrNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InsertVCRFineDtls", action = "http://tempuri.org/InsertVCRFineDtls")
    @WebResult(name = "InsertVCRFineDtlsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InsertVCRFineDtls", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertVCRFineDtls")
    @ResponseWrapper(localName = "InsertVCRFineDtlsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertVCRFineDtlsResponse")
    public String insertVCRFineDtls(
        @WebParam(name = "VCR_No", targetNamespace = "http://tempuri.org/")
        String vcrNo,
        @WebParam(name = "Regn_no", targetNamespace = "http://tempuri.org/")
        String regnNo,
        @WebParam(name = "Challan_no", targetNamespace = "http://tempuri.org/")
        String challanNo,
        @WebParam(name = "Transaction_no", targetNamespace = "http://tempuri.org/")
        String transactionNo,
        @WebParam(name = "Transaction_Amount", targetNamespace = "http://tempuri.org/")
        String transactionAmount,
        @WebParam(name = "Transaction_Dt", targetNamespace = "http://tempuri.org/")
        String transactionDt,
        @WebParam(name = "Payment_Dt", targetNamespace = "http://tempuri.org/")
        String paymentDt);

    /**
     * 
     * @param regnNo
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetTaxPaidVCRDetails", action = "http://tempuri.org/GetTaxPaidVCRDetails")
    @WebResult(name = "GetTaxPaidVCRDetailsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetTaxPaidVCRDetails", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTaxPaidVCRDetails")
    @ResponseWrapper(localName = "GetTaxPaidVCRDetailsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetTaxPaidVCRDetailsResponse")
    public String getTaxPaidVCRDetails(
        @WebParam(name = "RegnNo", targetNamespace = "http://tempuri.org/")
        String regnNo);

}
