
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LicRegVCRDetails", targetNamespace = "http://tempuri.org/", wsdlLocation = "classpath:WS.xml")
public class LicRegVCRDetails
    extends Service
{

    private final static URL LICREGVCRDETAILS_WSDL_LOCATION;
    private final static WebServiceException LICREGVCRDETAILS_EXCEPTION;
    private final static QName LICREGVCRDETAILS_QNAME = new QName("http://tempuri.org/", "LicRegVCRDetails");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("classpath:WS.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LICREGVCRDETAILS_WSDL_LOCATION = url;
        LICREGVCRDETAILS_EXCEPTION = e;
    }

    public LicRegVCRDetails() {
        super(__getWsdlLocation(), LICREGVCRDETAILS_QNAME);
    }

    public LicRegVCRDetails(WebServiceFeature... features) {
        super(__getWsdlLocation(), LICREGVCRDETAILS_QNAME, features);
    }

    public LicRegVCRDetails(URL wsdlLocation) {
        super(wsdlLocation, LICREGVCRDETAILS_QNAME);
    }

    public LicRegVCRDetails(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LICREGVCRDETAILS_QNAME, features);
    }

    public LicRegVCRDetails(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LicRegVCRDetails(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LicRegVCRDetailsSoap
     */
    @WebEndpoint(name = "LicRegVCRDetailsSoap")
    public LicRegVCRDetailsSoap getLicRegVCRDetailsSoap() {
        return super.getPort(new QName("http://tempuri.org/", "LicRegVCRDetailsSoap"), LicRegVCRDetailsSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LicRegVCRDetailsSoap
     */
    @WebEndpoint(name = "LicRegVCRDetailsSoap")
    public LicRegVCRDetailsSoap getLicRegVCRDetailsSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "LicRegVCRDetailsSoap"), LicRegVCRDetailsSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LICREGVCRDETAILS_EXCEPTION!= null) {
            throw LICREGVCRDETAILS_EXCEPTION;
        }
        return LICREGVCRDETAILS_WSDL_LOCATION;
    }

}
